### ISSUE TITLE
Como desarrollador buscaré APIs públicas para obtener información de los kanjis

### ISSUE THREAD

**Issue by velirean** [HanCharPI/han-character-back#1]
Buscar APIs que puedan decir el significado del kanji, pronunciación, versión en hiragana, cómo dibujar los trazos y otra información que sea relevante. Si no se encuentra una API pública entonces se anotará cuáles tendrán que implementarse a futuro junto con fuentes de información.

**Comment by Fer-Romero96** [comment]
1. https://kanjiapi.dev/
2. https://app.kanjialive.com/api/docs
3. https://github.com/onlyskin/kanjiapi.dev
4. https://github.com/Nippon2019/Handwritten-Japanese-Recognition/tree/master/Kanji
5. Swift: https://github.com/tuanna-hsp/kanji-handwriting-swift
6. https://towardsdatascience.com/creating-a-japanese-handwriting-recognizer-70be12732889
7. https://github.com/thebluber/kvg_kanji_recognizer
8. https://www.freecodecamp.org/news/build-a-handwriting-recognizer-ship-it-to-app-store-fcce24205b4b/
