### ISSUE TITLE
Separar servicios en el despliegue de Kubernetes para que no sea un sistema monolitico

### ISSUE THREAD

**Issue by velirean** [HanCharPI/han-character-back#10]
Actualmente todos los servicios se encuentran en un solo pod.

**Comment by Fer-Romero96** [comment]
COMANDOS UTILES
Para crear un deployment con la imagen que quieras
kubectl create deployment laravel --image= gcr.io/PROJECT_ID/laravel_k8_app:v2
kubectl create deployment mysql --image=mysql/mysql-server

Para Crear un balanceador de Cargas
kubectl expose deployment test2 --port 80 --type LoadBalancer

Entrar al pod que quieras
kubectl exec --stdin --tty laravel-567b894674-vvk54 -- /bin/bash

Generar la imagen de dcokerFile
docker build -t gcr.io/PROJECT_ID/laravel_k8_app:v1 .

Correr el la imagen del dockerfile localmente
docker run -p 43211:80 gcr.io/PROJECT_ID/laravel_k8_app:v1

Subir una imagen de docker a google cloud
docker push gcr.io/PROJECT_ID/laravel_k8_app:v1

LANZAMIENTO 
En el dockerfile copiar el .env de la unidad secret de google cloud
Crear la imagen de mysql y flask con sus balanceador de cargas para obtener las ips publicas
Actualizar el .env con las ips obtenidas  
Crear unidad secreta y subir el .env a google cloud
Actualizar el .yaml del pod para que monte la unidad secreta
Crear el pod y sacar su respectivo balanceador
Agregar certificados de https
