### ISSUE TITLE
Como programador, probaré la comunicación entre dockers de flask y MySQL

### ISSUE THREAD

**Issue by Fer-Romero96** [HanCharPI/han-character-back#2]

**Comment by velirean** [comment]
1. Tener docker de flask
2. Tener docker de MySQL
3. Hacer consulta a una tabla de MySQL desde el docker de flask
4. De ser posible crear un dockerfile con docker compose que configure ambos

**Comment by Fer-Romero96** [comment]
Debido a los problemas generados por flask decidimos desarrollar el back-end en laravel
